version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: "lets-plan-db"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "!ChangeMe!"
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: "!ChangeMe!"
    ports:
      - "3306:3306"
    volumes:
      - lets-plan-db:/var/lib/mysql
      - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - my-network
  php:
      container_name: "lets-plan-php"
      build:
        context: docker/php
      ports:
        - "8080:80"
      volumes:
        - ./:/var/www/html
      environment:
        APACHE_RUN_USER: www-data
        APACHE_RUN_GROUP: www-data
      networks:
        - my-network
      healthcheck:
        test: [ "CMD", "test -f var/lib/mysql/db" ]
        timeout: 20s
        retries: 10

networks:
  my-network:

volumes:
  lets-plan-db:

