version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: "lets-plan-db"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "!ChangeMe!"
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: "!ChangeMe!"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-network
  php:
      container_name: "lets-plan-php"
      build:
        context: docker/php
      ports:
        - "8080:80"
      volumes:
        - ./:/var/www/html
      environment:
        APACHE_RUN_USER: www-data
        APACHE_RUN_GROUP: www-data
      networks:
        - my-network

networks:
  my-network:

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
