name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start container
        shell: bash
        run: |
          docker-compose -f docker-compose.yml up -d --build
          docker ps
      - name: Run fixer and phpstan
        shell: bash
        run: |
          docker exec -t etsplan-backend_php composer phpstan
          docker exec -t etsplan-backend_php composer check-cs
      - name: Run Tests
        shell: bash
        run: |
          docker exec -t etsplan-backend_php composer behat_test
          docker exec -t etsplan-backend_php composer phpunit_test
      - name: Remove database
        shell: bash
        run: |
          docker exec -t etsplan-backend_php php bin/console doctrine:database:drop --force