name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: pawelwaw/docker-images:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: "install composer"
        run: composer install