name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "install composer/npm"
        run: |
          composer install
          npm install
          npm run dev
      - name: Start stack
        shell: bash
        run: |
          docker-compose -f docker-compose.yml up --verbose -d
          cp behat.yml.dist behat.yml
          docker ps
          docker network ls
          docker exec -t lets-plan-php ls -la
          docker exec -t lets-plan-php bin/console doctrine:migrations:migrate
          docker exec -t lets-plan-php bin/console doctrine:fixtures:load
          docker inspect lets-plan-db
          docker logs lets-plan-db
          docker exec -t lets-plan-php vendor/bin/behat