name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "install composer"
        run: composer install
      - name: Start stack
        shell: bash
        run: |
          docker-compose -f docker-compose.yml up -d
          docker ps